### ISSUE TITLE
Refactoring controller interaction script

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-unity#24] opened 2020-12-19 01:31 UTC
See https://gitlab.engr.illinois.edu/dev-studio/komodo/komodo_unity/-/issues/137 . 

@davtamay was this included in today's merge? Feel free to close if so.

**Comment by davtamay** [comment] 2021-02-24 21:04
duplicate of #11

**Closed as completed by davtamay** 2021-02-24 21:04 UTC
